/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataMahasiswa;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class DataForm extends javax.swing.JFrame {

    /**
     * Creates new form DataForm
     */
    String gender;
    String jurusan;
    public DataForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        RadioButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nimTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        semesterTxt = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        jurusanCbx = new javax.swing.JComboBox<>();
        costTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        presensiTxt = new javax.swing.JTextField();
        taskTxt = new javax.swing.JTextField();
        utsTxt = new javax.swing.JTextField();
        uasTxt = new javax.swing.JTextField();
        praktikumTxt = new javax.swing.JTextField();
        gradeTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextArea();
        countButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        regCb = new javax.swing.JCheckBox();
        utsCb = new javax.swing.JCheckBox();
        uasCb = new javax.swing.JCheckBox();
        regTxt = new javax.swing.JTextField();
        utsCbTxt = new javax.swing.JTextField();
        uasCbTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 139, 31));

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Jurusan");

        jLabel5.setText("Semester");

        RadioButton.add(maleButton);
        maleButton.setText("Laki - laki");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        RadioButton.add(femaleButton);
        femaleButton.setText("Perempuan");

        jurusanCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Teknik Komputer", "Teknik Elektro", "Teknik Mesin" }));
        jurusanCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanCbxActionPerformed(evt);
            }
        });

        jLabel6.setText("Biaya / Semester");

        jLabel7.setText("Total Kehadiran");

        jLabel8.setText("Nilai Tugas");

        jLabel9.setText("Nilai UTS");

        jLabel10.setText("Nilai UAS");

        jLabel11.setText("Grade");

        jLabel12.setText("Nilai Praktikum ");

        presensiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presensiTxtActionPerformed(evt);
            }
        });

        uasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nimTxt)
                    .addComponent(namaTxt)
                    .addComponent(maleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(femaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jurusanCbx, 0, 170, Short.MAX_VALUE)
                    .addComponent(semesterTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(costTxt))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(praktikumTxt)
                    .addComponent(gradeTxt)
                    .addComponent(uasTxt)
                    .addComponent(utsTxt)
                    .addComponent(taskTxt)
                    .addComponent(presensiTxt))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(presensiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)
                                .addComponent(utsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(taskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(uasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jurusanCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(praktikumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(semesterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(gradeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel6.setBackground(new java.awt.Color(1, 117, 112));

        outputTxt.setColumns(20);
        outputTxt.setRows(5);
        jScrollPane1.setViewportView(outputTxt);

        countButton.setText("HITUNG");
        countButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        tableButton.setText("KE TABEL");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(countButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(tableButton)
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(1, 117, 112));

        regCb.setText("Reg,");
        regCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCbActionPerformed(evt);
            }
        });

        utsCb.setText("UTS");
        utsCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsCbActionPerformed(evt);
            }
        });

        uasCb.setText("UAS");
        uasCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasCbActionPerformed(evt);
            }
        });

        regTxt.setText("0");

        utsCbTxt.setText("0");

        uasCbTxt.setText("0");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BIAYA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regCb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(utsCb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uasCb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(utsCbTxt)
                    .addComponent(uasCbTxt))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(84, 84, 84))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regCb)
                            .addComponent(regTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(utsCb))
                    .addComponent(utsCbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uasCb)
                    .addComponent(uasCbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uasTxtActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       nimTxt.setText("");
       namaTxt.setText("");
       costTxt.setText("");
       semesterTxt.setText("");
       presensiTxt.setText("");
       taskTxt.setText("");
       utsTxt.setText("");
       uasTxt.setText("");
       praktikumTxt.setText("");
       gradeTxt.setText("");
       regTxt.setText("0");
       utsCbTxt.setText("0");
       uasCbTxt.setText("0");
       outputTxt.setText("");
       RadioButton.clearSelection();
       jurusanCbx.setSelectedIndex(0);
       regCb.setSelected(false);
       utsCb.setSelected(false);
       uasCb.setSelected(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jurusanCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanCbxActionPerformed
        switch (jurusanCbx.getSelectedIndex()) {
            case 0:
                costTxt.setText("");
                break;
            case 1:
                costTxt.setText("5000000");
                break;
            case 2:
                costTxt.setText("4500000");
                break;
            default:
                costTxt.setText("4250000");
                break;
        }
    }//GEN-LAST:event_jurusanCbxActionPerformed

    private void regCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCbActionPerformed
       if(regCb.isSelected()){
           regTxt.setText("100000");
       } else {
           regTxt.setText("0");
       }
       
    }//GEN-LAST:event_regCbActionPerformed

    private void utsCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsCbActionPerformed
        if(utsCb.isSelected()){
           utsCbTxt.setText("300000");
       } else {
           utsCbTxt.setText("0");
       }
    }//GEN-LAST:event_utsCbActionPerformed

    private void uasCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasCbActionPerformed
        if(uasCb.isSelected()){
           uasCbTxt.setText("300000");
       } else {
           uasCbTxt.setText("0");
       }
    }//GEN-LAST:event_uasCbActionPerformed

    private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
        if (nimTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nim belum diisi");
    } else if (namaTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama belum diisi");
    } else if ((maleButton.isSelected() == false) && (femaleButton.isSelected() == false)) {
        JOptionPane.showMessageDialog(null, "Jenis kelamin belum dipilih");
    } else if (jurusanCbx.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(null, "Jurusan belum dipilih");
    } else if (presensiTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nilai kehadiran belum diisi");
    } else if (taskTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nilai tugas belum diisi");
    } else if (utsTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nilai UTS belum diisi");
    } else if (uasTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nilai UAS belum diisi");
    } else if (semesterTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semester belum diisi");
    } else {
        double presensiValue = Double.parseDouble(presensiTxt.getText());
        if (presensiValue > 14) {
            JOptionPane.showMessageDialog(null, "Nilai kehadiran tidak boleh lebih dari 14");
            return; // Menghentikan eksekusi selanjutnya jika nilai presensi melebihi 14
        }

        double taskValue = Double.parseDouble(taskTxt.getText());
        double utsValue = Double.parseDouble(utsTxt.getText());
        double uasValue = Double.parseDouble(uasTxt.getText());
        double regValue = Double.parseDouble(regTxt.getText());
        double utsCbValue = Double.parseDouble(utsCbTxt.getText());
        double uasCbValue = Double.parseDouble(uasCbTxt.getText());
        double praktikumValue, total;

        // Praktikum = 10% hadir + 20% tugas + 30% uts + 40% uas)
        praktikumValue = (((presensiValue + 86) * 10 / 100) + (taskValue * 20 / 100)
                + (utsValue * 30 / 100) + (uasValue * 40 / 100));
        praktikumTxt.setText(String.valueOf(praktikumValue));
        
        if(praktikumValue < 50){
            gradeTxt.setText("E");
        } else if(praktikumValue < 60){
            gradeTxt.setText("D");
        } else if(praktikumValue < 70){
            gradeTxt.setText("C");
        } else if(praktikumValue < 80){
            gradeTxt.setText("B");
        } else {
            gradeTxt.setText("A");
        }
        
        if(maleButton.isSelected()){
            femaleButton.setSelected(false);
            gender = "Laki - laki";
        } else {
            femaleButton.setSelected(true);
            maleButton.setSelected(false);
            gender = "Perempuan";
        }
        
        switch (jurusanCbx.getSelectedIndex()) {
            case 0:
                jurusan = " - ";
                break;
            case 1:
                jurusan = " Teknik Informatika ";
                break;
            case 2:
                jurusan = " Teknik Elektro ";       
                break;
            default:
                jurusan = " Teknik Mesin ";
                break;
        }
        total = regValue + utsCbValue + uasCbValue;
        
        outputTxt.setText("NIM \t: " + nimTxt.getText() + "\nNama \t: " 
                            + namaTxt.getText() + "\nJenis kelamin \t: " 
                            + gender + "\nJurusan \t: " 
                            + jurusan
                            + "\nSemester \t: " + semesterTxt.getText() 
                            + "\nNilai Praktikum \t: " 
                            + praktikumTxt.getText() + "\nGrade \t: " 
                            + gradeTxt.getText() + "\nTotal \t: " + total);
        }
    }//GEN-LAST:event_countButtonActionPerformed

    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
         if(nimTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nim belum diisi");
        } else if(namaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama belum diisi");
        } else if((maleButton.isSelected() == false) && (femaleButton.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Jenis kelamin belum dipilih");
        } else if(jurusanCbx.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Jurusan belum dipilih");
        } else if(presensiTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nilai kehadiran belum diisi");
        } else if(taskTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nilai tugas belum diisi");
        } else if(utsTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nilai UTS belum diisi");
        } else if(uasTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nilai UAS belum diisi");
        } else if(semesterTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Semester belum diisi");
        } else if(praktikumTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan tombol HITUNG terlebih dahulu");
        } else {
            if(maleButton.isSelected()){
            femaleButton.setSelected(false);
            gender = "Laki - laki";
            } else {
            femaleButton.setSelected(true);
            maleButton.setSelected(false);
            gender = "Perempuan";
            }
        
            switch (jurusanCbx.getSelectedIndex()) {
                case 0:
                    jurusan = " - ";
                    break;
                case 1:
                    jurusan = " Teknik Informatika ";
                    break;
                case 2:
                    jurusan = " Teknik Elektro ";       
                    break;
                default:
                    jurusan = " Teknik Mesin ";
                    break;
            }
            
            
            double regValue = Double.parseDouble(regTxt.getText()),
                utsCbValue = Double.parseDouble(utsCbTxt.getText()),
                uasCbValue = Double.parseDouble(uasCbTxt.getText()), total;
            total = regValue + utsCbValue + uasCbValue;
                    
            DataMahasiswa dataMahasiswa = new DataMahasiswa(nimTxt.getText(), namaTxt.getText(),
                                            gender, jurusan, semesterTxt.getText(), praktikumTxt.getText(),
                                            gradeTxt.getText(), total);
            dataMahasiswa.setVisible(true);
            
        }
    }//GEN-LAST:event_tableButtonActionPerformed

    private void presensiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presensiTxtActionPerformed
       
    }//GEN-LAST:event_presensiTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioButton;
    private javax.swing.JTextField costTxt;
    private javax.swing.JButton countButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField gradeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jurusanCbx;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nimTxt;
    private javax.swing.JTextArea outputTxt;
    private javax.swing.JTextField praktikumTxt;
    private javax.swing.JTextField presensiTxt;
    private javax.swing.JCheckBox regCb;
    private javax.swing.JTextField regTxt;
    private javax.swing.JTextField semesterTxt;
    private javax.swing.JButton tableButton;
    private javax.swing.JTextField taskTxt;
    private javax.swing.JCheckBox uasCb;
    private javax.swing.JTextField uasCbTxt;
    private javax.swing.JTextField uasTxt;
    private javax.swing.JCheckBox utsCb;
    private javax.swing.JTextField utsCbTxt;
    private javax.swing.JTextField utsTxt;
    // End of variables declaration//GEN-END:variables
}
